### ISSUE TITLE
Posters are event-specific

### ISSUE THREAD

**Issue by honzajavorek** [DjangoGirls/resources#14]
All the posters in resources are marked by date and place of the event, which makes them hard to re-use.

![screen shot 2015-05-15 at 15 02 19](https://cloud.githubusercontent.com/assets/283441/7653092/8933bcdc-fb13-11e4-99ad-36c72a1fe627.png)

Not everyone has Adobe Illustrator to edit the text or remove it. I vote for removing, so one could just download PDF and send it to printer :) :dog:

**Comment by olasitarska** [comment]
Hi,

This is because we have posters with Django and Python logo, which are trademarked. I don't know about Python, but I remember talking to Russ about Django trademark last year before we printed the first posters ever, and he said that if we want to comply with the trademark rules, we need to make the poster "event specific", not just a general "django" poster. This is why the dates are there.

But I agree that we can remove them from most of the posters. 

Mind that you don't have to have Adobe Illustrator, but basically any PDF/SVG editor, and there are free available on the market.

Cheers,
Ola

**Comment by honzajavorek** [comment]
Ah, now I see. That is a shame. We printed them as they are anyway and after all, it was not such an issue. Good point about the PDF/SVG editor - it did not came to my mind. Thanks! :balloon:
