### ISSUE TITLE
missing fonts for some design

### ISSUE THREAD

**Issue by thatdocslady** [DjangoGirls/resources#7]
Hiya, I tried to open the django box poster design in AI and it started yelling at me about missing fonts. I couldn't find the fonts anywhere in the repo, could someone please push them urgently? Got to send them to the printers ASAP... Thanks!

**Comment by olasitarska** [comment]
I think the only fonts there are these:
https://www.google.com/fonts/specimen/Lato
http://www.dafont.com/just-the-way-you-are.font

**Comment by aniav** [comment]
Fixed in 5778bf01b8b60ed092555572af1bcb095c73244e.

**Comment by thatdocslady** [comment]
Those are exactly the ones that are missing, but it would probably be more convenient if they were stored in a folder in OTF/TTF format so that when we edit the designs we can just install them on our computers. Thanks!!!

**Comment by aniav** [comment]
I have added the links in the Readme. If we add them as files in the repository we will be disconnected from the updates (that add some special characters quite often), or we would have to keep track of them. I am also not sure if we are allowed to copy the Lato font to our repository due to its license.
I think placing the links in Readme should do the trick.

**Comment by olasitarska** [comment]
:+1:

**Comment by thatdocslady** [comment]
Thanks! I also seem to be missing Lobster1.4, maybe that should go in the list too..,

**Comment by aniav** [comment]
I have added it. Thank you! :)
